FIND_PATH(OSL_INCLUDE_DIR osl/osl.h)

FIND_LIBRARY(OSL_LIBRARY NAMES osl)

IF (OSL_INCLUDE_DIR AND OSL_LIBRARY)
  SET(OSL_FOUND TRUE)
ENDIF (OSL_INCLUDE_DIR AND OSL_LIBRARY)


IF (OSL_FOUND)
  IF (NOT OSL_FIND_QUIETLY)
    MESSAGE(STATUS "Found OSL: ${OSL_LIBRARY}")
  ENDIF (NOT OSL_FIND_QUIETLY)
ELSE (OSL_FOUND)
  IF (OSL_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find OSL")
  ENDIF (OSL_FIND_REQUIRED)
ENDIF (OSL_FOUND)

